version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      DATASTORE: datastore:8080
      TIMESERIES: timeseries:8080
    networks:
      - pantogram

  datastore:
    build:
      context: .
      dockerfile: ./docker/datastore/Dockerfile
    environment:
      ENV: docker
      MYSQL_URL: mysql:3306
    volumes:
      - ./docker/datastore/script:/script
    entrypoint: /script/start.sh
    networks:
      - pantogram

  timeseries:
    build:
      context: .
      dockerfile: ./docker/timeseries/Dockerfile
    environment:
      ENV: docker
      INFLUXDB_URL: influxdb:8086
    volumes:
      - ./docker/timeseries/script:/script
    entrypoint: /script/start.sh
    networks:
      - pantogram

  mysql:
    build:
      context: ./docker/mysql
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pantogram
      MYSQL_PASSWORD: pantogram
      MYSQL_DATABASE: pantogram
      TZ: 'Asia/Tokyo'
    ports:
      - "53306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    networks: 
      - pantogram

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: pantogram
      INFLUXDB_USER_PASSWORD: pantogram
      INFLUXDB_DB: pantogram
    ports:
      - "8086:8086"
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb
    networks:
      - pantogram

  grafana:
    image: grafana/grafana:7.4.3
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
      - ./docker/grafana/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
      - ./docker/grafana/newsflash.yaml:/etc/grafana/provisioning/dashboards/newsflash.yaml
      - ./docker/grafana/newsflash.json:/var/lib/grafana/dashboards/newsflash/newsflash.json
    ports:
      - "3000:3000"
    networks:
      - pantogram

networks: 
  pantogram:
    name: pantogram
