// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: datastore/pb/pantogram.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_pb_pantogram_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_pb_pantogram_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_datastore_pb_pantogram_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RouteDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Company     string        `protobuf:"bytes,2,opt,name=Company,proto3" json:"Company,omitempty"`
	Prefectures []*Prefecture `protobuf:"bytes,3,rep,name=Prefectures,proto3" json:"Prefectures,omitempty"`
}

func (x *RouteDetail) Reset() {
	*x = RouteDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_pb_pantogram_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDetail) ProtoMessage() {}

func (x *RouteDetail) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_pb_pantogram_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDetail.ProtoReflect.Descriptor instead.
func (*RouteDetail) Descriptor() ([]byte, []int) {
	return file_datastore_pb_pantogram_proto_rawDescGZIP(), []int{1}
}

func (x *RouteDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RouteDetail) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *RouteDetail) GetPrefectures() []*Prefecture {
	if x != nil {
		return x.Prefectures
	}
	return nil
}

type Prefecture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *Prefecture) Reset() {
	*x = Prefecture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_pb_pantogram_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prefecture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prefecture) ProtoMessage() {}

func (x *Prefecture) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_pb_pantogram_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prefecture.ProtoReflect.Descriptor instead.
func (*Prefecture) Descriptor() ([]byte, []int) {
	return file_datastore_pb_pantogram_proto_rawDescGZIP(), []int{2}
}

func (x *Prefecture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prefecture) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_datastore_pb_pantogram_proto protoreflect.FileDescriptor

var file_datastore_pb_pantogram_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x70,
	0x61, 0x6e, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x62, 0x22, 0x1b, 0x0a, 0x05,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x77, 0x0a, 0x0b, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x3a, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x66, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x65, 0x66, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0b, 0x50, 0x72, 0x65, 0x66, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x22, 0x36, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x66, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x4f, 0x0a, 0x09, 0x44, 0x61,
	0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x1a, 0x19,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datastore_pb_pantogram_proto_rawDescOnce sync.Once
	file_datastore_pb_pantogram_proto_rawDescData = file_datastore_pb_pantogram_proto_rawDesc
)

func file_datastore_pb_pantogram_proto_rawDescGZIP() []byte {
	file_datastore_pb_pantogram_proto_rawDescOnce.Do(func() {
		file_datastore_pb_pantogram_proto_rawDescData = protoimpl.X.CompressGZIP(file_datastore_pb_pantogram_proto_rawDescData)
	})
	return file_datastore_pb_pantogram_proto_rawDescData
}

var file_datastore_pb_pantogram_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datastore_pb_pantogram_proto_goTypes = []interface{}{
	(*Route)(nil),       // 0: datastore.pb.Route
	(*RouteDetail)(nil), // 1: datastore.pb.RouteDetail
	(*Prefecture)(nil),  // 2: datastore.pb.Prefecture
}
var file_datastore_pb_pantogram_proto_depIdxs = []int32{
	2, // 0: datastore.pb.RouteDetail.Prefectures:type_name -> datastore.pb.Prefecture
	0, // 1: datastore.pb.Datastore.GetRouteDetail:input_type -> datastore.pb.Route
	1, // 2: datastore.pb.Datastore.GetRouteDetail:output_type -> datastore.pb.RouteDetail
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_datastore_pb_pantogram_proto_init() }
func file_datastore_pb_pantogram_proto_init() {
	if File_datastore_pb_pantogram_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datastore_pb_pantogram_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_pb_pantogram_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_pb_pantogram_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prefecture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datastore_pb_pantogram_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datastore_pb_pantogram_proto_goTypes,
		DependencyIndexes: file_datastore_pb_pantogram_proto_depIdxs,
		MessageInfos:      file_datastore_pb_pantogram_proto_msgTypes,
	}.Build()
	File_datastore_pb_pantogram_proto = out.File
	file_datastore_pb_pantogram_proto_rawDesc = nil
	file_datastore_pb_pantogram_proto_goTypes = nil
	file_datastore_pb_pantogram_proto_depIdxs = nil
}
