// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: timeseries/pb/pantogram.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteDetails []*RouteDetail `protobuf:"bytes,1,rep,name=RouteDetails,proto3" json:"RouteDetails,omitempty"`
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeseries_pb_pantogram_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeseries_pb_pantogram_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_timeseries_pb_pantogram_proto_rawDescGZIP(), []int{0}
}

func (x *SaveRequest) GetRouteDetails() []*RouteDetail {
	if x != nil {
		return x.RouteDetails
	}
	return nil
}

type RouteDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Company     string        `protobuf:"bytes,2,opt,name=Company,proto3" json:"Company,omitempty"`
	Prefectures []*Prefecture `protobuf:"bytes,3,rep,name=Prefectures,proto3" json:"Prefectures,omitempty"`
}

func (x *RouteDetail) Reset() {
	*x = RouteDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeseries_pb_pantogram_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDetail) ProtoMessage() {}

func (x *RouteDetail) ProtoReflect() protoreflect.Message {
	mi := &file_timeseries_pb_pantogram_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDetail.ProtoReflect.Descriptor instead.
func (*RouteDetail) Descriptor() ([]byte, []int) {
	return file_timeseries_pb_pantogram_proto_rawDescGZIP(), []int{1}
}

func (x *RouteDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RouteDetail) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *RouteDetail) GetPrefectures() []*Prefecture {
	if x != nil {
		return x.Prefectures
	}
	return nil
}

type Prefecture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *Prefecture) Reset() {
	*x = Prefecture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeseries_pb_pantogram_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prefecture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prefecture) ProtoMessage() {}

func (x *Prefecture) ProtoReflect() protoreflect.Message {
	mi := &file_timeseries_pb_pantogram_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prefecture.ProtoReflect.Descriptor instead.
func (*Prefecture) Descriptor() ([]byte, []int) {
	return file_timeseries_pb_pantogram_proto_rawDescGZIP(), []int{2}
}

func (x *Prefecture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prefecture) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeseries_pb_pantogram_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeseries_pb_pantogram_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_timeseries_pb_pantogram_proto_rawDescGZIP(), []int{3}
}

var File_timeseries_pb_pantogram_proto protoreflect.FileDescriptor

var file_timeseries_pb_pantogram_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x2f,
	0x70, 0x61, 0x6e, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x22, 0x4d,
	0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x78, 0x0a,
	0x0b, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x50, 0x72,
	0x65, 0x66, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0b, 0x50, 0x72, 0x65, 0x66,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x66, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x0e, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x59, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x4b, 0x0a,
	0x0e, 0x53, 0x61, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x1a, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timeseries_pb_pantogram_proto_rawDescOnce sync.Once
	file_timeseries_pb_pantogram_proto_rawDescData = file_timeseries_pb_pantogram_proto_rawDesc
)

func file_timeseries_pb_pantogram_proto_rawDescGZIP() []byte {
	file_timeseries_pb_pantogram_proto_rawDescOnce.Do(func() {
		file_timeseries_pb_pantogram_proto_rawDescData = protoimpl.X.CompressGZIP(file_timeseries_pb_pantogram_proto_rawDescData)
	})
	return file_timeseries_pb_pantogram_proto_rawDescData
}

var file_timeseries_pb_pantogram_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_timeseries_pb_pantogram_proto_goTypes = []interface{}{
	(*SaveRequest)(nil),  // 0: timeseries.pb.SaveRequest
	(*RouteDetail)(nil),  // 1: timeseries.pb.RouteDetail
	(*Prefecture)(nil),   // 2: timeseries.pb.Prefecture
	(*SaveResponse)(nil), // 3: timeseries.pb.SaveResponse
}
var file_timeseries_pb_pantogram_proto_depIdxs = []int32{
	1, // 0: timeseries.pb.SaveRequest.RouteDetails:type_name -> timeseries.pb.RouteDetail
	2, // 1: timeseries.pb.RouteDetail.Prefectures:type_name -> timeseries.pb.Prefecture
	0, // 2: timeseries.pb.Timeseries.SaveTimeseries:input_type -> timeseries.pb.SaveRequest
	3, // 3: timeseries.pb.Timeseries.SaveTimeseries:output_type -> timeseries.pb.SaveResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_timeseries_pb_pantogram_proto_init() }
func file_timeseries_pb_pantogram_proto_init() {
	if File_timeseries_pb_pantogram_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timeseries_pb_pantogram_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeseries_pb_pantogram_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeseries_pb_pantogram_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prefecture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeseries_pb_pantogram_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timeseries_pb_pantogram_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timeseries_pb_pantogram_proto_goTypes,
		DependencyIndexes: file_timeseries_pb_pantogram_proto_depIdxs,
		MessageInfos:      file_timeseries_pb_pantogram_proto_msgTypes,
	}.Build()
	File_timeseries_pb_pantogram_proto = out.File
	file_timeseries_pb_pantogram_proto_rawDesc = nil
	file_timeseries_pb_pantogram_proto_goTypes = nil
	file_timeseries_pb_pantogram_proto_depIdxs = nil
}
