// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TimeseriesClient is the client API for Timeseries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeseriesClient interface {
	SaveTimeseries(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
}

type timeseriesClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeseriesClient(cc grpc.ClientConnInterface) TimeseriesClient {
	return &timeseriesClient{cc}
}

func (c *timeseriesClient) SaveTimeseries(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/timeseries.pb.Timeseries/SaveTimeseries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeseriesServer is the server API for Timeseries service.
// All implementations must embed UnimplementedTimeseriesServer
// for forward compatibility
type TimeseriesServer interface {
	SaveTimeseries(context.Context, *SaveRequest) (*SaveResponse, error)
	mustEmbedUnimplementedTimeseriesServer()
}

// UnimplementedTimeseriesServer must be embedded to have forward compatible implementations.
type UnimplementedTimeseriesServer struct {
}

func (UnimplementedTimeseriesServer) SaveTimeseries(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTimeseries not implemented")
}
func (UnimplementedTimeseriesServer) mustEmbedUnimplementedTimeseriesServer() {}

// UnsafeTimeseriesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeseriesServer will
// result in compilation errors.
type UnsafeTimeseriesServer interface {
	mustEmbedUnimplementedTimeseriesServer()
}

func RegisterTimeseriesServer(s grpc.ServiceRegistrar, srv TimeseriesServer) {
	s.RegisterService(&Timeseries_ServiceDesc, srv)
}

func _Timeseries_SaveTimeseries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeseriesServer).SaveTimeseries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timeseries.pb.Timeseries/SaveTimeseries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeseriesServer).SaveTimeseries(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Timeseries_ServiceDesc is the grpc.ServiceDesc for Timeseries service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Timeseries_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "timeseries.pb.Timeseries",
	HandlerType: (*TimeseriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveTimeseries",
			Handler:    _Timeseries_SaveTimeseries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timeseries/pb/pantogram.proto",
}
